base_images:
  base:
    name: ubi-minimal
    namespace: ocp
    tag: "8"
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.14
images:
- dockerfile_path: Dockerfile.prow
  from: base
  to: metrics-collector
promotion:
  name: latest
  namespace: open-cluster-management
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: unit
  commands: |
    export SELF="make -f Makefile.prow"
    make -f Makefile.prow unit-tests
  container:
    from: bin
- as: sonar
  commands: |
    export SELF="make -f Makefile.prow"
    make -f Makefile.prow sonar/go/prow
  container:
    from: src
  secrets:
  - mount_path: /etc/sonarcloud/
    name: acm-sonarcloud-token
zz_generated_metadata:
  branch: main
  org: open-cluster-management
  repo: metrics-collector
